import Link from "next/link";
import { notFound } from "next/navigation";
import { requireUser } from "@/lib/auth/session";
import { getTopicVocabulary } from "@/lib/vocabulary/service";
import { setVocabularyLearnedAction } from "@/lib/vocabulary/actions";
import { ProgressBar } from "@/components/progress-bar";
import { SpeakerButton } from "@/components/speaker-button";

function dbLevel(level: string) { return level === "level-1" ? "LEVEL_1" : level === "level-2" ? "LEVEL_2" : null; }

export default async function TopicPage({ params, searchParams }: { params: Promise<{ level: string; topic: string }>; searchParams: Promise<{ filter?: string; q?: string }> }) {
  const [{ level, topic }, search] = await Promise.all([params, searchParams]); const mapped = dbLevel(level); if (!mapped) notFound();
  const filter = search.filter === "learned" || search.filter === "not-learned" ? search.filter : "all";
  const user = await requireUser(); const data = await getTopicVocabulary(user.id, mapped, topic, { filter, query: search.q?.trim() || "" }); if (!data) notFound();
  const notLearned = data.total - data.learned;
  const filters = [["all", `All (${data.total})`], ["not-learned", `Not learned (${notLearned})`], ["learned", `Learned (${data.learned})`]] as const;
  return <div><Link href={`/app/vocabulary/${level}`} className="text-sm text-gray-500">← {mapped === "LEVEL_1" ? "Level 1" : "Level 2"}</Link><div className="mt-5 flex flex-wrap items-end justify-between gap-4"><div><h1 className="text-2xl font-semibold">{data.topic.name} — {mapped === "LEVEL_1" ? "Level 1" : "Level 2"}</h1><p className="muted mt-2 text-sm">{data.learned} / {data.total} learned</p></div></div><div className="mt-3 max-w-xl"><ProgressBar value={data.learned} max={data.total} /></div>
    <div className="mt-6 flex flex-col gap-3 lg:flex-row lg:items-center lg:justify-between"><div className="flex flex-wrap gap-2">{filters.map(([key, label]) => <Link key={key} href={`?filter=${key}${search.q ? `&q=${encodeURIComponent(search.q)}` : ""}`} className={`rounded-md border px-3 py-2 text-sm ${filter === key ? "border-gray-900 bg-gray-900 text-white" : "border-gray-200 bg-white"}`}>{label}</Link>)}</div><form className="flex gap-2"><input type="hidden" name="filter" value={filter} /><label className="sr-only" htmlFor="topic-search">Search in this topic</label><input id="topic-search" name="q" defaultValue={search.q || ""} placeholder="Search in this topic" className="input min-w-64" /><button className="btn-secondary">Search</button></form></div>
    <div className="mt-5 space-y-3">{data.items.length ? data.items.map(item => { const learned = item.progress[0]?.learned ?? false; const family = Array.isArray(item.wordFamily) ? item.wordFamily as string[] : []; const collocations = Array.isArray(item.collocations) ? item.collocations as string[] : []; return <article key={item.id} className="surface p-4"><div className="flex flex-wrap items-start gap-3"><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h2 className="text-lg font-semibold">{item.word}</h2><SpeakerButton word={item.word} /></div><div className="mt-1 text-sm text-gray-500">{item.ipa} · {item.partOfSpeech}</div><div className="mt-2 text-sm">{item.vietnameseMeaning}</div></div><form action={setVocabularyLearnedAction}><input type="hidden" name="vocabularyItemId" value={item.id} /><input type="hidden" name="learned" value={learned ? "false" : "true"} /><button className={learned ? "btn-secondary" : "btn-primary"}>{learned ? "Mark as not learned" : "Mark as learned"}</button></form></div><details className="mt-4 border-t border-gray-100 pt-3"><summary className="cursor-pointer text-sm font-medium">Word details</summary><div className="mt-3 grid gap-3 text-sm leading-6 md:grid-cols-2"><div><span className="font-medium">Reading definition:</span> {item.readingDefinition}</div><div><span className="font-medium">Example:</span> {item.exampleSentence}</div><div><span className="font-medium">Word family:</span> {family.join(", ") || "—"}</div><div><span className="font-medium">Collocations:</span> {collocations.join(", ") || "—"}</div></div></details></article>; }) : <div className="surface p-5"><p className="font-medium">No vocabulary matches this view</p><p className="muted mt-1 text-sm">Change the filter or search term.</p></div>}</div>
  </div>;
}
