import Link from "next/link";
import { AdminPageHeader, StatusPill } from "@/components/admin/ui";
import { prisma } from "@/lib/db";

export default async function AdminAiPage(){
  const since=new Date(Date.now()-7*86_400_000);
  const [plans,modelStats,recentFailures]=await Promise.all([
    prisma.plan.findMany({orderBy:{sortOrder:"asc"},include:{aiConfig:true}}),
    prisma.aiCallLog.groupBy({by:["model","status"],where:{createdAt:{gte:since}},_count:{_all:true},_sum:{totalTokens:true,costUsd:true,latencyMs:true}}),
    prisma.aiCallLog.findMany({where:{status:"FAILURE"},orderBy:{createdAt:"desc"},take:30,include:{user:{select:{username:true}},plan:{select:{displayName:true}}}})
  ]);
  return <div><AdminPageHeader title="AI / Models" description="OpenRouter is the provider boundary. Plan and stage model IDs are operational database configuration, so the next submission can change model without a code deploy."/>
    <section className="surface p-5"><div className="mb-4 flex items-center justify-between"><div><h2 className="font-semibold">Plan pipeline configuration</h2><p className="mt-1 text-sm text-zinc-500">Global fallback: <span className="font-mono">{process.env.OPENROUTER_MODEL||"not configured"}</span></p></div></div><div className="table-wrap"><table><thead><tr><th>Plan</th><th>Pipeline</th><th>Default</th><th>Task 1 overrides</th><th>Task 2 overrides</th><th/></tr></thead><tbody>{plans.map(p=><tr key={p.id}><td><div className="font-medium">{p.displayName}</div><StatusPill value={p.visibility}/></td><td>{p.aiRequestsPerSubmission} request{p.aiRequestsPerSubmission===1?"":"s"}</td><td className="max-w-xs break-all font-mono text-xs">{p.defaultModel||"Fallback env"}</td><td className="max-w-sm text-xs text-zinc-500"><div>Vision: {p.aiConfig?.task1VisionModel||"default"}</div><div>Examiner: {p.aiConfig?.task1ExaminerModel||"default"}</div><div>Verifier: {p.aiConfig?.task1VerifierModel||"default"}</div><div>Feedback: {p.aiConfig?.task1FeedbackModel||"default"}</div></td><td className="max-w-sm text-xs text-zinc-500"><div>Examiner: {p.aiConfig?.task2ExaminerModel||"default"}</div><div>Verifier: {p.aiConfig?.task2VerifierModel||"default"}</div><div>Feedback: {p.aiConfig?.task2FeedbackModel||"default"}</div><div>Teaching: {p.aiConfig?.task2TeachingModel||"default"}</div></td><td><Link className="text-sm font-semibold" href={`/admin/plans/${p.id}`}>Configure →</Link></td></tr>)}</tbody></table></div></section>
    <div className="mt-5 grid gap-5 xl:grid-cols-2"><section className="surface p-5"><h2 className="font-semibold">Model usage · 7 days</h2><div className="table-wrap mt-4"><table><thead><tr><th>Model</th><th>Status</th><th>Calls</th><th>Tokens</th><th>Cost</th></tr></thead><tbody>{modelStats.map((s,i)=><tr key={`${s.model}-${s.status}-${i}`}><td className="max-w-52 break-all font-mono text-xs">{s.model}</td><td><StatusPill value={s.status}/></td><td>{s._count._all}</td><td>{s._sum.totalTokens||"—"}</td><td>{s._sum.costUsd?`$${Number(s._sum.costUsd).toFixed(6)}`:"—"}</td></tr>)}</tbody></table></div></section><section className="surface p-5"><h2 className="font-semibold">Recent failures</h2>{recentFailures.length?<div className="mt-4 max-h-[560px] space-y-3 overflow-auto">{recentFailures.map(l=><div key={l.id} className="rounded-xl border border-zinc-200 p-3"><div className="flex justify-between gap-2"><div className="text-sm font-medium">{l.user.username} · {l.plan.displayName}</div><span className="text-xs text-zinc-400">{l.createdAt.toLocaleString("en-GB")}</span></div><div className="mt-1 text-xs text-zinc-500">{l.stage} · {l.errorCategory||"UNKNOWN"}</div><div className="mt-1 break-all font-mono text-xs text-zinc-400">{l.model}</div>{l.sanitizedError?<div className="mt-2 text-xs text-red-600">{l.sanitizedError}</div>:null}<Link className="mt-2 inline-block text-xs font-semibold" href={`/admin/ai/${l.logicalSubmissionId}`}>Open pipeline →</Link></div>)}</div>:<p className="mt-4 text-sm text-zinc-500">No failures recorded.</p>}</section></div>
  </div>;
}
