import { requireAdmin } from "@/lib/auth/session";
import { prisma } from "@/lib/db/prisma";
import { normalizeUsername } from "@/lib/validation/auth";
import { getEntitlementSummary } from "@/lib/entitlements/service";
import { grantProAction, resetUserPasswordAction, revokeProAction, setCustomProExpiryAction } from "@/lib/admin/actions";

export default async function AdminUsersPage({ searchParams }: { searchParams: Promise<{ q?: string }> }) {
  await requireAdmin(); const { q = "" } = await searchParams;
  const users = await prisma.user.findMany({ where: q ? { normalizedUsername: { contains: normalizeUsername(q) } } : undefined, orderBy: { createdAt: "desc" }, take: 50 });
  const rows = await Promise.all(users.map(async user => { const entitlement = await getEntitlementSummary(user.id); const pro = await prisma.entitlementPeriod.findFirst({ where: { userId: user.id, plan: "PRO", isActive: true, endAt: { gt: new Date() } }, orderBy: { endAt: "desc" } }); return { user, entitlement, pro }; }));
  return <div><h1 className="text-2xl font-semibold">Users</h1><form className="mt-5 flex max-w-lg gap-2"><input className="input" name="q" defaultValue={q} placeholder="Search username" /><button className="btn-secondary">Search</button></form><div className="mt-6 space-y-4">{rows.map(({ user, entitlement, pro }) => <article key={user.id} className="surface p-5"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="font-semibold">{user.username} <span className="text-xs font-normal text-gray-500">{user.role}</span></h2><p className="muted mt-1 text-sm">Registered {user.createdAt.toLocaleString("en-GB")}</p></div><div className="text-right text-sm"><div className="font-medium">{entitlement.plan} · {entitlement.quotaUsed}/{entitlement.quotaLimit} used</div><div className="muted mt-1">Pro expiry: {entitlement.proExpiry?.toLocaleString("en-GB") || "—"}</div><div className="muted">Pro source: {pro?.source || "—"}</div></div></div><div className="mt-5 grid gap-3 border-t border-gray-100 pt-4 lg:grid-cols-4"><form action={grantProAction}><input type="hidden" name="userId" value={user.id} /><button className="btn-secondary w-full">Grant / extend Pro 30d</button></form><form action={revokeProAction}><input type="hidden" name="userId" value={user.id} /><button className="btn-secondary w-full">Revoke Pro</button></form><form action={setCustomProExpiryAction} className="flex gap-2"><input type="hidden" name="userId" value={user.id} /><input className="input" name="expiry" placeholder="2026-09-30T20:00:00+07:00" required /><button className="btn-secondary">Set expiry</button></form><form action={resetUserPasswordAction} className="flex gap-2"><input type="hidden" name="userId" value={user.id} /><input className="input" name="newPassword" type="password" placeholder="New password" minLength={8} required /><button className="btn-secondary">Reset</button></form></div></article>)}</div></div>;
}
