import Link from "next/link";
import { ArrowRight, BookOpenText, PenLine } from "lucide-react";
import { requireUser } from "@/lib/auth";
import { getCreditSummary } from "@/lib/services/credits";
import { vocabularyLevelsForUser } from "@/lib/services/vocabulary";
import { prisma } from "@/lib/db";

export default async function DashboardPage() {
  const user=await requireUser();
  const [credits,levels,recent]=await Promise.all([
    getCreditSummary(user.id), vocabularyLevelsForUser(user.id),
    prisma.writingSubmission.findMany({where:{userId:user.id},orderBy:{createdAt:"desc"},take:4,include:{result:{select:{overallBand:true}}}})
  ]);
  return <div><div className="mb-7"><p className="text-sm text-zinc-500">Welcome back, {user.username}</p><h1 className="mt-1 text-2xl font-semibold tracking-tight">Dashboard</h1></div><div className="grid gap-4 lg:grid-cols-2"><section className="surface p-5"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><BookOpenText size={18}/><h2 className="font-semibold">Vocabulary</h2></div><Link href="/app/vocabulary" className="text-sm font-semibold">Open →</Link></div><div className="mt-5 space-y-4">{levels.map(level=>{const p=level.total?Math.round(level.learned/level.total*100):0;return <div key={level.id}><div className="mb-1.5 flex justify-between text-sm"><span>{level.name} <span className="text-zinc-400">{level.bandRange}</span></span><span className="text-zinc-500">{p}%</span></div><div className="h-1.5 rounded-full bg-zinc-100"><div className="h-full rounded-full bg-zinc-900" style={{width:`${p}%`}}/></div></div>})}</div></section><section className="surface p-5"><div className="flex items-center gap-2"><PenLine size={18}/><h2 className="font-semibold">Writing</h2></div><div className="mt-5"><div className="text-4xl font-semibold tracking-tight">{credits.totalRemaining}</div><div className="mt-1 text-sm text-zinc-500">Submissions remaining</div><div className="mt-3 text-xs text-zinc-400">{credits.planRemaining} plan · {credits.bonusRemaining} bonus</div></div><Link href="/app/writing" className="btn btn-primary mt-6">Start Writing <ArrowRight size={15}/></Link></section></div><section className="mt-4 surface p-5"><div className="flex items-center justify-between"><h2 className="font-semibold">Recent Writing</h2><Link href="/app/history" className="text-sm font-semibold">View history →</Link></div>{recent.length?<div className="mt-4 divide-y divide-zinc-100">{recent.map(item=><Link href={`/app/history/${item.id}`} key={item.id} className="flex items-center gap-4 py-3 first:pt-0 last:pb-0"><div className="min-w-0 flex-1"><div className="text-xs font-semibold text-zinc-400">{item.taskType==="TASK_1"?"Task 1":"Task 2"}</div><div className="truncate text-sm font-medium">{item.questionTitle}</div><div className="mt-1 text-xs text-zinc-400">{item.createdAt.toLocaleDateString("en-GB")} · {item.wordCount} words</div></div><div className="text-sm font-semibold">BAND <span className="text-red-600">{item.result?.overallBand.toFixed(1)}</span></div></Link>)}</div>:<p className="mt-4 text-sm text-zinc-500">No Writing submissions yet.</p>}</section></div>;
}
