import Link from "next/link";
import { updateReportStatusAction } from "@/actions/admin";
import { AdminPageHeader, EmptyAdmin, StatusPill } from "@/components/admin/ui";
import { prisma } from "@/lib/db";

export default async function AdminReportsPage({searchParams}:{searchParams:Promise<{status?:string}>}){
  const {status}=await searchParams; const allowed=["OPEN","REVIEWING","RESOLVED","DISMISSED"]; const filter=allowed.includes(status||"")?status as "OPEN"|"REVIEWING"|"RESOLVED"|"DISMISSED":undefined;
  const reports=await prisma.problemReport.findMany({where:filter?{status:filter}:undefined,orderBy:{createdAt:"desc"},take:150,include:{user:{select:{username:true}},submission:{select:{questionTitle:true,taskType:true,result:{select:{overallBand:true}}}}}});
  return <div><AdminPageHeader title="Reports" description="Each report stays linked to the original learner response, verified result and AI pipeline metadata. Learners never need to paste the essay again."/>
    <div className="mb-5 flex flex-wrap gap-2"><Link className={`btn ${!filter?"btn-primary":"btn-secondary"}`} href="/admin/reports">All</Link>{allowed.map(s=><Link key={s} className={`btn ${filter===s?"btn-primary":"btn-secondary"}`} href={`/admin/reports?status=${s}`}>{s}</Link>)}</div>
    {reports.length?<div className="table-wrap"><table><thead><tr><th>Reporter</th><th>Problem</th><th>Submission</th><th>Status</th><th>Review</th></tr></thead><tbody>{reports.map(r=><tr key={r.id}><td><Link className="font-medium" href={`/admin/users/${r.userId}`}>{r.user.username}</Link><div className="text-xs text-zinc-400">{r.createdAt.toLocaleString("en-GB")}</div></td><td><div className="font-medium">{r.category.replaceAll("_"," ")}</div>{r.message?<div className="mt-1 max-w-md text-sm text-zinc-500">{r.message}</div>:null}</td><td><div className="max-w-md truncate text-sm">{r.submission.taskType==="TASK_1"?"Task 1":"Task 2"} · {r.submission.questionTitle}</div><div className="text-xs text-zinc-400">Band {r.submission.result?.overallBand.toFixed(1)||"—"}</div><Link className="mt-1 inline-block text-sm font-semibold" href={`/admin/writing/${r.submissionId}`}>Inspect submission →</Link></td><td><StatusPill value={r.status}/></td><td><form action={updateReportStatusAction.bind(null,r.id)} className="flex min-w-52 gap-2"><select className="input" name="status" defaultValue={r.status}>{allowed.map(s=><option key={s} value={s}>{s}</option>)}</select><button className="btn btn-secondary">Save</button></form></td></tr>)}</tbody></table></div>:<EmptyAdmin>No grading reports in this view.</EmptyAdmin>}
  </div>;
}
