import Link from "next/link";
import { notFound } from "next/navigation";
import { AdminPageHeader, Section, StatusPill } from "@/components/admin/ui";
import { prisma } from "@/lib/db";

function arrayText(value: unknown): string[] { return Array.isArray(value) ? value.map(String) : []; }
function pretty(value: unknown) { return JSON.stringify(value, null, 2); }
const criterionOrder: Record<string, number> = { taskCriterion: 0, coherenceCohesion: 1, lexicalResource: 2, grammaticalRangeAccuracy: 3 };

export default async function AdminWritingDetailPage({params}:{params:Promise<{id:string}>}){
  const {id}=await params;
  const [submission,logs]=await Promise.all([
    prisma.writingSubmission.findUnique({where:{id},include:{user:{select:{username:true}},plan:{select:{displayName:true,slug:true}},result:{include:{criteria:true}},reports:{orderBy:{createdAt:"desc"}}}}),
    prisma.aiCallLog.findMany({where:{logicalSubmissionId:id},orderBy:{startedAt:"asc"}})
  ]);
  if(!submission)notFound(); const result=submission.result;
  const totalLatency=logs.reduce((sum,l)=>sum+l.latencyMs,0); const totalTokens=logs.reduce((sum,l)=>sum+(l.totalTokens||0),0); const totalCost=logs.reduce((sum,l)=>sum+Number(l.costUsd||0),0);
  return <div><AdminPageHeader title="Writing submission" description={submission.id} actions={<Link className="btn btn-secondary" href="/admin/writing">Back</Link>}/>
    <div className="mb-5 grid gap-4 sm:grid-cols-2 xl:grid-cols-5"><div className="surface p-4"><div className="text-xs text-zinc-500">User</div><Link href={`/admin/users/${submission.userId}`} className="mt-1 block font-semibold">{submission.user.username}</Link></div><div className="surface p-4"><div className="text-xs text-zinc-500">Task</div><div className="mt-1 font-semibold">{submission.taskType==="TASK_1"?"Task 1":"Task 2"}</div></div><div className="surface p-4"><div className="text-xs text-zinc-500">Plan snapshot</div><div className="mt-1 font-semibold">{submission.planNameSnapshot}</div></div><div className="surface p-4"><div className="text-xs text-zinc-500">Pipeline</div><div className="mt-1 font-semibold">{submission.pipelineSize} AI request{submission.pipelineSize===1?"":"s"}</div></div><div className="surface p-4"><div className="text-xs text-zinc-500">Overall</div><div className="mt-1 text-xl font-semibold">{result?.overallBand.toFixed(1)||"—"}</div></div></div>
    <div className="grid gap-5 xl:grid-cols-[minmax(0,1.25fr)_minmax(340px,.75fr)]"><div className="space-y-5">
      <Section title="Question"><div className="font-medium">{submission.questionTitle}</div>{submission.questionText?<pre className="mt-3 whitespace-pre-wrap rounded-xl bg-zinc-50 p-4 text-sm leading-6">{submission.questionText}</pre>:null}{submission.normalizedQuestion?<details className="mt-3"><summary className="cursor-pointer text-sm font-semibold">Normalized Task 1 visual extraction</summary><pre className="mt-2 max-h-96 overflow-auto rounded-xl bg-zinc-950 p-4 text-xs text-zinc-100">{pretty(submission.normalizedQuestion)}</pre></details>:null}</Section>
      <Section title="Learner response" description={`${submission.wordCount} words`}><pre className="whitespace-pre-wrap text-sm leading-7">{submission.essayText}</pre></Section>
      {result?<Section title="Criterion scores"><div className="space-y-4">{[...result.criteria].sort((a,b)=>(criterionOrder[a.key]??99)-(criterionOrder[b.key]??99)).map(c=><div key={c.id} className="rounded-xl border border-zinc-200 p-4"><div className="flex items-center justify-between gap-4"><div className="font-semibold">{c.name}</div><div className="text-xl font-semibold">{c.band.toFixed(1)}</div></div><p className="mt-2 text-sm text-zinc-600">{c.summary}</p><div className="mt-3 grid gap-3 md:grid-cols-2"><div><div className="text-xs font-semibold uppercase tracking-wide text-zinc-400">Evidence</div><ul className="mt-1 list-disc space-y-1 pl-5 text-sm">{arrayText(c.evidence).map((x,i)=><li key={i}>{x}</li>)}</ul></div><div><div className="text-xs font-semibold uppercase tracking-wide text-zinc-400">Limiting weaknesses</div><ul className="mt-1 list-disc space-y-1 pl-5 text-sm">{arrayText(c.limitingWeaknesses).map((x,i)=><li key={i}>{x}</li>)}</ul></div></div></div>)}</div></Section>:null}
      {result?<Section title="Verifier & feedback metadata"><div className="text-sm"><strong>Main issue:</strong> {result.mainIssue}</div>{result.verifierMetadata?<pre className="mt-3 overflow-auto rounded-xl bg-zinc-950 p-4 text-xs text-zinc-100">{pretty(result.verifierMetadata)}</pre>:<p className="mt-2 text-sm text-zinc-500">Single-request pipeline; no independent verifier metadata.</p>}</Section>:null}
      <Section title="User reports">{submission.reports.length?<div className="space-y-3">{submission.reports.map(r=><div key={r.id} className="rounded-xl border p-3"><div className="flex justify-between gap-3"><span className="font-medium">{r.category.replaceAll("_"," ")}</span><StatusPill value={r.status}/></div>{r.message?<p className="mt-2 text-sm text-zinc-600">{r.message}</p>:null}</div>)}</div>:<p className="text-sm text-zinc-500">No grading reports.</p>}</Section>
    </div><aside className="space-y-5">
      <Section title="Pipeline totals"><dl className="space-y-3 text-sm"><div className="flex justify-between"><dt className="text-zinc-500">Calls logged</dt><dd className="font-medium">{logs.length}</dd></div><div className="flex justify-between"><dt className="text-zinc-500">Latency</dt><dd className="font-medium">{totalLatency.toLocaleString()} ms</dd></div><div className="flex justify-between"><dt className="text-zinc-500">Tokens</dt><dd className="font-medium">{totalTokens||"—"}</dd></div><div className="flex justify-between"><dt className="text-zinc-500">Provider cost</dt><dd className="font-medium">{totalCost?`$${totalCost.toFixed(6)}`:"—"}</dd></div><div className="flex justify-between"><dt className="text-zinc-500">Rubric</dt><dd className="font-mono text-xs">{submission.rubricVersion}</dd></div><div className="flex justify-between"><dt className="text-zinc-500">Prompt</dt><dd className="font-mono text-xs">{submission.promptVersion}</dd></div></dl></Section>
      <Section title="AI calls">{logs.length?<div className="space-y-4">{logs.map((l,i)=><div key={l.id} className="border-b border-zinc-100 pb-4 last:border-0 last:pb-0"><div className="flex items-start justify-between gap-2"><div><div className="text-xs text-zinc-400">Request {i+1}</div><div className="font-medium">{l.stage}</div></div><StatusPill value={l.status}/></div><div className="mt-2 break-all text-xs text-zinc-500">{l.model}</div><dl className="mt-2 grid grid-cols-2 gap-1 text-xs text-zinc-500"><dt>Latency</dt><dd>{l.latencyMs} ms</dd><dt>HTTP</dt><dd>{l.providerStatus||"—"}</dd><dt>Tokens</dt><dd>{l.totalTokens||"—"}</dd><dt>Cost</dt><dd>{l.costUsd?`$${Number(l.costUsd).toFixed(6)}`:"—"}</dd></dl>{l.status==="FAILURE"?<div className="mt-2 rounded-lg bg-red-50 p-2 text-xs text-red-700">{l.errorCategory||"UNKNOWN"}{l.sanitizedError?`: ${l.sanitizedError}`:""}</div>:null}</div>)}</div>:<p className="text-sm text-zinc-500">No AI logs found.</p>}</Section>
    </aside></div>
  </div>;
}
